### PR TITLE
implements arrow

### PR DESCRIPTION
**Pull request by MrGumpIT**
add arrow shape
add arrow icon
add arrow icon in dialog

Can you implement rendering like you did for the triangle?

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Hmm do you think this is a basic shape? I'm more thinking about adding arrows, stars and more as a component in the core pack.

**Comment by CodeDoctorDE** [comment]
The thing is: I don't want to add more things that we need in the basic shapes. Otherwise it gets very crowded.
Maybe we can use this principle: everything that can be detected by the shape detection is a basic shape that we could add.

For an arrow you have the problem that you can have a dotted line, a full sarrow head, a outlined, ...

**Comment by MrGumpIT** [comment]
we can do so.  Where should I start from to add the basic package?

**Comment by CodeDoctorDE** [comment]
Hmm, I dont like zip/bfly files in this repo. What do you think about making it code driven?
A generateCorePack function that adds these things?
Currently the pack uses the old json format. Maybe we should readd this format if we dont use the other idea?

**Comment by CodeDoctorDE** [comment]
The getCorePack is inside the defaults.dart

**Comment by MrGumpIT** [comment]
what if we simply had SVGs as templates, loaded via json

**Comment by CodeDoctorDE** [comment]
Hmm yeah... SVGs are really cool.
We need to look about the license of these to add this.
But maybe not really for arrows. If you want to make the line of the arrow longer, you also make the head longer...
Hmm that's very tricky

**Comment by CodeDoctorDE** [comment]
i would close this for now... feel free to open another pr if you are done.
Maybe we should implement something like a "Anchor" (like in figma) to deal with sizing

**Pull request closed without merging**
