### PR TITLE
change logic of eraser

### PR DESCRIPTION
**Pull request by MrGumpIT**
The main difference is the change in how it's detected if a stroke should be erased. Now, a stroke is erased only if the square of the distance between the current pointer position and the last erased position is greater than or equal to the square of the eraser's stroke width. Moreover, if a point of the stroke is too close to the pointer position, that point is omitted, a new path is started, and the stroke is marked as "broken". If a stroke has been broken, then it is always modified, even if it has only one path.
It would be interesting to set the default size of the eraser equal to the size of the pen and see how it works, I have not been able to do it.
solve #461

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Thanks for fixing this. I will test it out tomorrow.
If you want you can join the discord (https://linwood.dev/discord) or matrix server (https://linwood.dev/matrix) and we can talk about the app further.

From the first view it looks good.

**Comment by CodeDoctorDE** [comment]
Hi, I tried it and sometimes it leaves small points. I don't know if this is an issue here but it would be nice if we could fix this somehow.
Btw: If you write `Closes: #461` instead of `solve #461` it automatically closes the issue when merging it. It would be nice if you can join the matrix or discord server to talk

**Comment by MrGumpIT** [comment]
I tried to solve it in many ways but without success, it happens when you try to break a line, this is because we don't delete the point directly but we overwrite it.  For now I think it's an acceptable compromise: you get fewer points than before and they can still be cancelled.  I'll keep trying anyway.  I joined the discord you should be able to see me

**Comment by CodeDoctorDE** [comment]
Yeah,
I'm the same opinion, I will merge it.
What's your name on discord, I can't find your name on the Linwood discord

**Pull request merged**
