### PR TITLE
Improve dav performance

### PR DESCRIPTION
**Pull request by MrGumpIT**

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Does it really help the performance? Looks like a small change I could merge quickly

**Comment by MrGumpIT** [comment]
improves a lot, less UI lag, for me it worked very well, you can try it too

**Review by CodeDoctorDE — APPROVED** [review]
lgtm, i need to look if I want to put it in 2.1.1 or in 2.2 nightly

**Comment by CodeDoctorDE** [comment]
thanks for contribution. will be added in 2.1.1-rc.0

**Pull request merged**
