### PR TITLE
Advance areas

### LINKED ISSUE #574: [Feature request]: Add area navigator page
### Is your feature request related to a problem? Please describe

Organising areas can be difficult.

### Describe your feature request!

Add an area navigator page to list all areas alphabetically (or custom) to edit/delete/teleport/enter them.

### Additional context

Related to #573

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
Closes #574

### CODE REVIEW

**Comment by Luciogi** [comment]
working great on desktop

**Comment by CodeDoctorDE** [comment]
Thanks <3

**Comment by Luciogi** [comment]
On android area tweaking handles are not appearing!

**Comment by CodeDoctorDE** [comment]
you need to click on the area you want to change to show the controls (if you are testing this branch. it's currently not in the nightly versions)

**Comment by Luciogi** [comment]
> you need to click on the area you want to change to show the controls (if you are testing this branch. it's currently not in the nightly versions)

I am testing this branch

**Comment by Luciogi** [comment]
[screen-20240220-174325 (1).webm](https://github.com/LinwoodDev/Butterfly/assets/84625092/4e34f39c-d694-4398-be17-346b8150e5cc)



area is not drawn correctly:
- From button to top
- Right to Left

**Comment by CodeDoctorDE** [comment]
Thanks for testing, I will fix that

**Comment by CodeDoctorDE** [comment]
fixed

**Pull request merged**
