### PR TITLE
solve pdf export problem

### PR DESCRIPTION
**Pull request by MrGumpIT**
i try it on windows and android he works correctly, scale factor is no longer necessary, you should change the dropdown menu to have the user select landscape mode.

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Hmm, but the idea was that the pdf page is the same size as the area to have a similar export behavior as image and svg. Now it is a4 no matter how the area was before. And I don't see the dpi anywhere relevant? The exact slider value is just the visual representation of the tool.constrainedWidth

**Comment by MrGumpIT** [comment]
Maybe I misunderstood, I understood that the objective was to obtain an A4 sized page on which the area with the drawings were correctly shown.  The dpi is multiplied by the height and width in area.dart to make sure that the drawing area always has the same physical size on all devices, also I tried to use the same dimensions for the area and l image but there is something that breaks because I get large white borders around the image or a small image in different positions of the pdf

**Comment by CodeDoctorDE** [comment]
Yeah, but maybe the FullPage and the fit: fill should work?

**Comment by MrGumpIT** [comment]
Mhh I don't know, I also tried to provide fixed dimensions, and while the other exports worked and gave the correct dimensions, the PDF export didn't, because the page always has different dimensions even if the page is created with the same area dimensions.  This seemed like the best and most functional solution to me

**Comment by CodeDoctorDE** [comment]
I close this pr now to keep it clean here. If you have another fix feel free to open a new one

**Pull request closed without merging**
