### PR TITLE
Improve image

### PR DESCRIPTION
**Pull request by MrGumpIT**
solve #704 
I don't know if it is necessary to use `Paint()..filterQuality = FilterQuality.high;` elsewhere in the code.
However, it seems to have improved the problem.
If it could be useful:https://stackoverflow.com/questions/72508103/improve-scaled-image-aliasing-in-canvas

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Looks good to me, but try excluding pubspec.lock out of the commits. For this one, it looks okay since it just upgrades the current onces

**Comment by MrGumpIT** [comment]
can you modify in this: 
`var paint = Paint()
      ..filterQuality = FilterQuality.high
      ..isAntiAlias = true;,`
 without me making another commit? because I deleted the branch

**Comment by CodeDoctorDE** [comment]
Sure, i will do it when im at home

**Comment by MrGumpIT** [comment]
thanks, I only just discovered that it exists and it further improves the quality

**Comment by CodeDoctorDE** [comment]
added

**Pull request merged**
