### PR TITLE
Semi-Automatic Builds For Butterfly Snap

### PR DESCRIPTION
**Pull request by CapeCrusader321**
@CodeDoctorDE 
This will bring some automation as no need to specify new source file every-time but will only work if manually triggered or pushed for builds....

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Thanks!
I will test everything today before merging.
> Please keep this format for releases permanent, dont change this format for releases as this automation is built around this style --> https://github.com/LinwoodDev/Butterfly/releases/download/v2.0.0-alpha.2/linwood-butterfly-linux.tar.gz

What do you mean?
I use these tags:

For nightly versions
* Prerelease + v as first character
* `nightly`

For stable versions
* Stable release + v as first character
* `stable`

**Comment by CodeDoctorDE** [comment]
ignore the failing build, I had to upgrade to the newest flutter version

**Comment by CapeCrusader321** [comment]
> Thanks! I will test everything today before merging.
> 
> > Please keep this format for releases permanent, dont change this format for releases as this automation is built around this style --> https://github.com/LinwoodDev/Butterfly/releases/download/v2.0.0-alpha.2/linwood-butterfly-linux.tar.gz
> 
> What do you mean? I use these tags:
> 
> For nightly versions
> 
>     * Prerelease + v as first character
> 
>     * `nightly`
> 
> 
> For stable versions
> 
>     * Stable release + v as first character
> 
>     * `stable`

Please read the override-pull part and see how i tried to automate the link, as per the info we will have to change it in future again as currently its styled after alpha one, i will explain you in the future in more detail

**Comment by CapeCrusader321** [comment]
@CodeDoctorDE 
Its fine, in other projects the 'v' conflicted the version variable and thus i couldnt automate, but here your release format is better, it doesnt conflict, i was just telling to keep it as it  is ....

**Comment by CodeDoctorDE** [comment]
Yeah,
On all my projects I have the same tag naming convention

**Comment by CapeCrusader321** [comment]
> Yeah, On all my projects I have the same tag naming convention

@CodeDoctorDE  Your alpha that is version 2 is beautiful, i tested it ....

sc

**Comment by CodeDoctorDE** [comment]
Thanks, feel free to report bugs and request features.
I would continue this conversation on matrix/discord if you want and keep this pr clean for the automatic topic

**Pull request merged**
