### PR TITLE
prevented creation of files outside of a folder

### PR DESCRIPTION
**Pull request by MrGumpIT**
it was not possible to create a file, except inside a subfolder

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
https://pub.dev/documentation/path/latest/path/split.html i don't understand, this should do the same?

**Comment by MrGumpIT** [comment]
i add some print for test, and this is the result: Restarted application in 1.343ms.
flutter: dynamic_color: Accent color detected.
flutter: Original path: /test2.bfly
flutter: Path split using /: [, test2.bfly]
flutter: Path split using p.split: [/, test2.bfly]
flutter: Running on platform: windows
flutter: Document is cached, updating cache content.
flutter: Directory path: /
flutter: Creating request to overwrite the file at: /test2.bfly
flutter: Request URL parts: [/, test2.bfly]
flutter: Request method: PUT

**Comment by CodeDoctorDE** [comment]
But the slash also exist on split. Maybe we should remove the leading slash before with an if condition?

**Comment by MrGumpIT** [comment]
if I remove/it works, I remove it just for the request

**Comment by CodeDoctorDE** [comment]
thanks for contributing!

**Pull request merged**
