### PR TITLE
solve render page problem with pdf

### PR DESCRIPTION
**Pull request by MrGumpIT**
It seems to solve the problem of when you write on a PDF on Android, and it gets blurred and the strokes disappear

### CODE REVIEW

**Comment by MrGumpIT** [comment]
this seems to have solved the problem when I import a pdf, if I import another the problem still exists, but only if I write on the second pdf

**Comment by CodeDoctorDE** [comment]
Hmm this can't be the solution since it just says when it should reset it's current state and start baking completly new.
Ceil ist just another round function that rounds it to the newest integer

**Comment by MrGumpIT** [comment]
no it is not

**Comment by CodeDoctorDE** [comment]
I will close it for now to keep the opened pull requests organized a bit. Feel free to open a new one if you fixed the bug

**Pull request closed without merging**
